
max-gamma = 150

# Profile 1: Daytime 
profile {
    time = 07:00
    identity = true
    gamma = 1.0
}

# Profile 2: Evening (Slightly warm)
profile {
    time = 19:30
    temperature = 4000
    gamma = 0.9
}

# Profile 3: Late Night (Very warm)
profile {
    time = 22:30
    temperature = 2500
    gamma = 0.8
}


